name: morpheus
description: The ultimate sleep analysis and dream tracking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^7.0.1
  intl: ^0.17.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  health: ^6.0.0
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_app_check: ^0.1.4+1
  firebase_storage: ^11.2.1
  firebase_analytics: ^10.4.1
  cloud_firestore: ^4.7.1
  ionicons: ^0.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf